apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toqqer-test-pvc
  namespace: toqqer-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
