apiVersion: v1
kind: Secret
metadata:
  name: toqqer-secret
  namespace: toqqer-test
type: Opaque
data:
  username: dG9xcWVybWFzdGVy
  password: dG9xcWVybWFzdGVy
  jwt-token: dG9xcWVyYXBwbGljYXRpb25oeWRlcmFiYWQxMjM0NTY3ODl0b3FxZXJhcHBsaWNhdGlvbmh5ZGVyYWJhZDEyMzQ1Njc4OQ==
  activemq-username: YWRtaW4=
  activemq-password: YWRtaW4=
  activemq-topic: ZXZlbnREYXRhVG9waWM=
  kaleyra-sid: SFhJTjE3OTUzMDU2MDlJTg==
  kaleyra-apikey: QTljZWU2MGMyYTM5OThjNGEwZDI1YTVhYWZjMjUxYTZl
  kaleyra-senderid: VklER0FU
  kaleyra-templateid: MTAwNzM5MDUwNjQwNzQ5ODU2NA==
  twilio-account-sid: QUMwZTFkMGMxM2FhODViOTQ5ZTcwMDg3Y2RmZjE2ZjI0Mw==
  twilio-auth-token: MzcwZWEyOGZlZjYwZGI1ZmUyM2MxZWEyMzllNjVjNDk=
  twilio-number: KzE0MDkyMTUzMjEz
  vonage-api-key: NzU3MmZkYmE=
  vonage-api-secret: Z0ZNbU9qVmVCbDc4UmxLRg==
  spring-datasource-username: dG9xcWVybWFzdGVy
  spring-datasource-password: dG9xcWVybWFzdGVy
  jwt-tokenValidity: ODY0MDAwMDA=
  spring-datasource-driver-class-name: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy
  spring-mail-host: c210cC5nbWFpbC5jb20=
  spring-mail-port: NTg3
  spring-mail-username: Y3VzdG9tZXJjYXJlQHRvcXFlci5jb20=
  spring-mail-password: YmJhdHNicXFucWZlam10bw==
  spring-mail-properties-mail-smtp-auth: dHJ1ZQ==
  spring-mail-properties-mail-smtp-connectiontimeout: NTAwMA==
  spring-mail-properties-mail-smtp-timeout: NTAwMA==
  spring-mail-properties-mail-smtp-writetimeout: NTAwMA==
  spring-mail-properties-mail-smtp-starttls-enable: dHJ1ZQ==
  keyId: Nzk1N2FlOWE4NmE1NTdiNDk5YTI0YmFiNjhlMDkwMTg=
  encKey: NDUxMjZmZGIyNjZjMjVlNzkwZDI2NzczYzM4NGY2MjA=
  pssh: MDAwMDAwNTQ3MDczNzM2ODAwMDAwMDAwRURFRjhCQTk3OUQ2NEFDRUEzQzgyN0RDRDUxRDIxRUQwMDAwMDAzNDA4MDExMjEwNzk1N2FlOWE4NmE1NTdiNDk5YTI0YmFiNjhlMDkwMTgxYTA4NmQ2Zjc2Njk2NDZmNmU2NTIyMTA1OTA0NDNkZGE2NDg3ZjRlYmIxNTMxY2EyYjc5Yzk0MzJhMDI1MzQ0
  appId: MTAwMzY3ZmNiNGY0NjdhMWE0NTg0ZTc0ZWI3NjMwMDE=
  appSecretKey: N2MyMjQ0NGMwYmFiODAzMzM0M2FjMzFiMjcwZWMwYzdjMmVjMjE2ZA==
